"""Pydantic schemas package."""

from schemas.document import (
    ChapterCreateRequest,
    ChapterResponse,
    ChapterUpdateRequest,
    DocumentNodeSchema,
    ParagraphCreateRequest,
    ParagraphResponse,
    ParagraphUpdateRequest,
    PartCreateRequest,
    PartResponse,
    PartUpdateRequest,
    SectionCreateRequest,
    SectionResponse,
    SectionUpdateRequest,
    SentenceCreateRequest,
    SentenceResponse,
    SentenceUpdateRequest,
    StructuredDocumentSchema,
)

__all__ = [
    "ChapterCreateRequest",
    "ChapterResponse",
    "ChapterUpdateRequest",
    "DocumentNodeSchema",
    "ParagraphCreateRequest",
    "ParagraphResponse",
    "ParagraphUpdateRequest",
    "PartCreateRequest",
    "PartResponse",
    "PartUpdateRequest",
    "SectionCreateRequest",
    "SectionResponse",
    "SectionUpdateRequest",
    "SentenceCreateRequest",
    "SentenceResponse",
    "SentenceUpdateRequest",
    "StructuredDocumentSchema",
]
